# checkov:skip=CKV_DOCKER_2:Healthcheck instructions have not been added to container images
# checkov:skip=CKV_DOCKER_3:"Ensure that a user for the container has been created"
# checkov:skip=CKV_DOCKER_7:the official bash Docker images don't tag specific versions 

FROM bash:latest
COPY tests /tests
