---
name: RStudio Build & Test

"on":
  pull_request:
  push: { branches: [main] }

jobs:
  yamllint:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  docker:
    runs-on: [self-hosted]
    env:
      REPOSITORY: rstudio
      IMAGE_TAG: ${{ github.sha }}
      REGISTRY: "593291632749"
    needs: [mdl, yamllint]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.REGISTRY }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: make build
        env: { NETWORK: host }
        working-directory: ${{env.working-directory}}
      - name: Test
        run: make test
        env: { CHEF_LICENSE: accept-no-persist }
      - name: Push image
        run: make push
        working-directory: ${{ env.working-directory }}
