---
name: RStudio Build & Test

"on":
  pull_request:
  push: { branches: [main] }

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@master

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  ecr:
    runs-on: analytics-platform-rstudio
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "593291632749"

  docker:
    needs: [mdl, yamllint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Test
        run: make test
        env: { CHEF_LICENSE: accept-no-persist }
