---
name: RStudio Build & Test

"on":
  pull_request:
  push: { branches: [main] }

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@master

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  ecr:
    runs-on: [self-hosted]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "593291632749"
      - name: Echo version of aws-cli
        uses: hannut91/aws-cli@1.18.65
        with:
          args: --version        
      - name: Check out code
        uses: actions/checkout@master
      - name: Build tag and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rstudio
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  docker:
    needs: [mdl, yamllint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Test
        run: make test
        env: { CHEF_LICENSE: accept-no-persist }
