---
name: 🩻 Scan

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build
        id: build
        shell: bash
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make build

      - name: Scan
        id: scan
        run: exit 0 # trivy-action step removed
