---
name: 🧪 Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/github-actions/setup-container-structure-test@db1a54895bf5fb975c60af47e5a3aab96505ca3e # v18.6.0

      - name: Build
        id: build
        shell: bash
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: make build

      - name: Test
        id: test
        shell: bash
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: make clean && make test
